<?php

// Database configuration
$host = 'localhost';
$db   = 'ostad';
$user = 'root';
$pass = '';
$charset = 'utf8mb4';

// Set up database connection using PDO
$options = [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES   => false,
];

try {
    $dsn = "mysql:host=$host;dbname=$db;charset=$charset";
    $pdo = new PDO($dsn, $user, $pass, $options);
} catch (\PDOException $e) {
    throw new \PDOException($e->getMessage(), (int)$e->getCode());
}

// SQL query to retrieve total revenue generated by each category
// SQL query to retrieve total revenue generated by each category
$sql = "SELECT 
            Categories.name AS category_name,
            SUM(Order_Items.quantity * Order_Items.unit_price) AS total_revenue
        FROM 
            Categories
        JOIN Products ON Categories.category_id = Products.category_id
        JOIN Order_Items ON Products.product_id = Order_Items.product_id
        GROUP BY 
            Categories.name
        ORDER BY 
            total_revenue DESC";



// Execute the query
$stmt = $pdo->prepare($sql);
$stmt->execute();

// Fetch the results
$results = $stmt->fetchAll();

// Display the results
echo "<h2>Total Revenue by Category</h2>";
echo "<table border='1'>";
echo "<tr>
        <th>Category Name</th>
        <th>Total Revenue</th>
      </tr>";

foreach ($results as $row) {
    echo "<tr>
            <td>" . htmlspecialchars($row["category_name"]) . "</td>
            <td>" . htmlspecialchars($row["total_revenue"]) . "</td>
          </tr>";
}
echo "</table>";

// Close connection
$pdo = null;
?>
